name: Build Images and Deploy

on:
  push:
    branches:
      - main

env:
  NEXUS_URL: ${{secrets.NEXUS_URL}}
  NEXUS_USERNAME: ${{secrets.NEXUS_USERNAME}}
  NEXUS_PASSWORD: ${{secrets.NEXUS_PASSWORD}}
  IMAGE_REPO_NAME: ${{secrets.IMAGE_REPO_NAME}}

jobs:
  build:
    runs-on: self-hosted
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Login to Nexus Docker Registry
      run: echo "${{ env.NEXUS_PASSWORD }}" | docker login -u "${{ env.NEXUS_USERNAME }}" --password-stdin ${{ env.NEXUS_URL }}
    - name: Build Docker Image
      run: docker build -t ${{ env.NEXUS_USERNAME }}/${{ env.IMAGE_REPO_NAME }}:latest .
    - name: Push Docker Image
      run: docker push ${{ env.NEXUS_URL }}/${{ env.IMAGE_REPO_NAME }}:latest



#  steps:
#    - name: Checkout Repository
#      uses: actions/checkout@v2
#
#    - name: Log into Nexus Docker Registry
#      run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin your-nexus-url:your-nexus-port
#
#    - name: Build and Push Docker Image
#      run: |
#        docker build -t your-nexus-url:your-nexus-port/your-image:your-tag .
#        docker push your-nexus-url:your-nexus-port/your-image:your-tag
#  deploy:
#    name: Deploy
#    if: github.ref == 'refs/heads/main'
#    needs: [build]
#    runs-on: ubuntu-latest
#    steps:
#    - name: Kubernetes Set Context
#      uses: azure/k8s-set-context@v1
#      with:
#        method: kubeconfig
#        kubeconfig: ${{ secrets.KUBE_CONFIG }}
#    - name: Checkout
#      uses: actions/checkout@v2
#    - name: Deploy
#      uses: azure/k8s-deploy@v1
#      with:
#          manifests: |
#            deployments/clusterrole.yaml
#            deployments/app-deployment.yaml
#            deployments/serviceaccount-secret.yaml
#          images: |
#            ${{ env.DOCKER_USERNAME }}/${{ env.IMAGE_REPO_NAME }}:latest
#          imagepullsecrets: |
#            docker-credentials
#          namespace: default
#          strategy: recreate