name: Build Images and Deploy

on:
  push:
    branches:
      - master
    workflows_dispatch:

env:
  DOCKER_USERNAME: ${{secrets.DOCKER_USERNAME}}
  DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
  IMAGE_REPO_NAME: ${{secrets.IMAGE_REPO_NAME}}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
      username: ${{ env.DOCKER_USERNAME }}
      password: ${{ env.DOCKER_PASSWORD }}
    - name: Build and Push
      uses: docker/build-push-action@v2
      with:
      push: true
      tags: ${{ env.IMAGE_REPO_NAME }}:latest
