name: Build Images and Deploy

on:
  push:
    branches:
      - main

env:
  DOCKER_USERNAME: ${{secrets.DOCKER_USERNAME}}
  DOCKER_ACCESS_TOKEN: ${{secrets.DOCKER_ACCESS_TOKEN}}
  IMAGE_REPO_NAME: ${{secrets.IMAGE_REPO_NAME}}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Login to DockerHub
      uses: docker/login-action@v3
      with:
        username: ${{ env.DOCKER_USERNAME }}
        password: ${{ env.DOCKER_ACCESS_TOKEN }}
    - name: Build and Push
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: ${{ env.DOCKER_USERNAME }}/${{ env.IMAGE_REPO_NAME }}:latest
  deploy:
    name: Deploy
    if: github.ref == 'refs/heads/main'
    needs: [build]
    runs-on: ubuntu-latest
    steps:
    - name: Kubernetes Set Context
      uses: azure/k8s-set-context@v1
      with:
        method: kubeconfig
        kubeconfig: ${{ secrets.KUBE_CONFIG }}
    - name: Checkout
      uses: actions/checkout@v2
    - name: Deploy
      uses: azure/k8s-deploy@v1
      with:
          manifests: |
            deployments/clusterrole.yaml
            deployments/app-deployment.yaml
            deployments/serviceaccount-secret.yaml
          images: |
            ${{ env.DOCKER_USERNAME }}/${{ env.IMAGE_REPO_NAME }}:latest
          imagepullsecrets: |
            docker-credentials
          namespace: default
          strategy: recreate